flex/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import datetime

from flex import db
from flex.forms import MemberCreateForm, MemberLoginForm, NonmemberLoginForm, NonmemberReservationForm, ReservationCancelForm
from flex.models import Member, Nonmember, Reservation, Movie, Screenschedule, Theater, Seat, Screen, Pay, Cancel, Membership
import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup', methods=('GET', 'POST'))
def signup():
    form = MemberCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        member = Member.query.filter_by(id=form.id.data).first()
        if not member:
            member = Member(id=form.id.data,
                            pw=generate_password_hash(form.password1.data),
                            birth_date=form.birth_date.data,
                            name=form.name.data,
                            phone=form.phone.data,
                            email=form.email.data,
                            nickname=form.nickname.data)
            membership = Membership(rank='브론즈',
                                    point=500,
                                    member_id=form.id.data)
            db.session.add(membership)
            db.session.add(member)
            db.session.commit()
            member.membership_id=membership.id
            db.session.commit()
            return redirect(url_for('main.init'))
        else:
            flash('이미 가입된 사용자입니다.')
    return render_template('client_templates/auth/signup.html', form=form)

@bp.route('/login', methods=('GET', 'POST'))
def login():
    form = MemberLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        member = Member.query.filter_by(id=form.id.data).first()
        if not member:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(member.pw, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['member_id'] = member.id
            return redirect(url_for('main.init'))
        flash(error)
    return render_template('client_templates/auth/login.html', form=form)

@bp.route('/guest', methods=('GET', 'POST'))
def guest_login():
    form = NonmemberLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        guest = Nonmember.query.filter_by(phone=form.phone.data).first()
        if not guest:
            guest = Nonmember(phone=form.phone.data,
                              name=form.name.data,
                              pw=generate_password_hash(form.password.data),
                              birth_date=form.birth_date.data)                
            db.session.add(guest)
            db.session.commit()
            session.clear()
            session['nonmember_phone'] = guest.phone
        else:
            guest.pw = generate_password_hash(form.password.data)
            db.session.commit()
            session.clear()
            session['nonmember_phone'] = guest.phone
        return redirect(url_for('reservation.ticket'))
    return render_template('client_templates/auth/guest.html', form=form)

@bp.route('/guest/reservation', methods=('GET', 'POST'))
def guest_reservation():
    form = NonmemberReservationForm()
    reservations = []
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        guest = Nonmember.query.filter_by(phone=form.phone.data).first()
        if not guest:
            error = "예매내역이 존재하지 않는 사용자입니다."
        elif not check_password_hash(guest.pw, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        elif (guest.birth_date != form.birth_date.data) :
            error = "생년월일이 올바르지 않습니다."
        else:
            reservations = Reservation.query.filter(Reservation.nonmember_phone == guest.phone).all()
            reservation_list = []
            for reservation in reservations:
                screenschedule_list = []
                screenschedules = Screenschedule.query.filter(Screenschedule.id == reservation.screen_schedule_id).all()
                for screenschedule in screenschedules :
                    movies = Movie.query.filter(Movie.id == screenschedule.movie_id).all()
                    theaters = Theater.query.filter(Theater.id == screenschedule.theater_id).all()
                    screens = Screen.query.filter(Screen.number == screenschedule.screen_number).first()
                    screenschedule_list.append(dict(id=screenschedule.id, session=screenschedule.session, starttime=screenschedule.starttime, endtime=screenschedule.endtime, screen=screens, movies=movies, theaters=theaters))
                seat_list = reservation.seats.split()
                res_seat_list = []
                for i in range(len(seat_list)):
                    seat = Seat.query.get(seat_list[i])
                    res_seat_list.append(seat)
                reservation_list.append(dict(id=reservation.id, date=reservation.date, seat=res_seat_list, screen_number=reservation.seat_screen_number, screenschedules = screenschedule_list))
            return render_template('client_templates/auth/guest_reservationlist.html', reservations=reservation_list)
        flash(error)
    return render_template('client_templates/auth/guest_reservation.html', form=form)

@bp.route('/<int:res_id>', methods=('POST', 'GET'))
def cancel(res_id):
    reservation = Reservation.query.get(res_id)
    schedule = Screenschedule.query.get(reservation.screen_schedule_id)
    movie = Movie.query.get(schedule.movie_id)
    screen = Screen.query.get(schedule.screen_number)
    pay = Pay.query.filter(Pay.reservation_id == res_id).first()
    seat_list = reservation.seats.split()
    theater_name = Theater.query.get(schedule.theater_id)
    query_seat_list = []
    coupon_value = 0
    form = ReservationCancelForm()
    for j in range(len(seat_list)):
        seat = Seat.query.get(seat_list[j])
        query_seat_list.append(seat)
    if request.method == 'POST' and form.validate_on_submit():
        for seat in query_seat_list:
            seat.available=1
            db.session.add(seat)
        db.session.delete(pay)
        db.session.delete(reservation)
        db.session.commit()
        return redirect((url_for('auth.guest_reservation')))
    return render_template('client_templates/cancel-reservation.html', reservation = reservation, schedule = schedule, movie = movie,
                           pay = pay, query_seat_list = query_seat_list, theater_name=theater_name, screen=screen, coupon_value = coupon_value, form=form)

@bp.route('/login/<int:movie_id>/movie', methods=('GET', 'POST'))  # 추가.
def login_movie(movie_id):
    form = MemberLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        member = Member.query.filter_by(id=form.id.data).first()
        if not member:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(member.pw, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['member_id'] = member.id
            return redirect(url_for('movies.detail', movie_id=movie_id))
        flash(error)
    return render_template('client_templates/auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_member():
    member_id = session.get('member_id')
    if member_id is None:
        g.member = None
    else:
        g.member = Member.query.get(member_id)

@bp.before_app_request
def load_logged_in_guest():
    nonmember_phone = session.get('nonmember_phone')
    if nonmember_phone is None:
        g.guest = None
    else:
        g.guest = Nonmember.query.get(nonmember_phone)


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.init'))

# 추가
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.member is None:    # g.user 수정
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

flex/views/movies_views.py
from flask import Blueprint, url_for, render_template, g, request, flash
from werkzeug.utils import redirect

from datetime import datetime

from ..views.auth_views import login_required

from flex import db
from flex.forms import ReviewForm
from flex.models import Movie, Actor, Review

bp = Blueprint('movies', __name__, url_prefix='/movies')

#영화 목록 페이지
@bp.route('/')
def list():
    movie_list = Movie.query.order_by(Movie.id.asc())
    rate_list = []
    for movie in movie_list:
        this_list = []
        review_list = Review.query.filter(Review.movie_id == movie.id).all()
        sum = 0
        num = 0
        for review in review_list:
            sum += review.rate
            num += 1
        if(num > 0):
            rate = round(sum / num, 2)
        else:
            rate = 0
        this_list.append(movie)
        this_list.append(rate)
        rate_list.append(this_list)
    return render_template('client_templates/movies-list.html', rate_list=rate_list)

#영화 목록 페이지에서 영화 이름 누르면 해당 영화 detail 페이지 랜더링, 각 영화의 이미지, 이름 등 db에 있는 정보들을 인자로 넘겨서 랜더링

@bp.route('/detail/<int:movie_id>')
def detail(movie_id):
    movie = Movie.query.get(movie_id)
    actor_list = Actor.query.filter(Actor.movie_id == movie_id).all()
    review_list = Review.query.filter(Review.movie_id == movie_id).all()
    sum = 0
    for review in review_list:
        sum += review.rate
    if len(review_list) != 0:
        rate = round(sum / len(review_list),2)
    else:
        rate = 0
    return render_template('client_templates/movie-info-sidebar-right.html', movie=movie, actor_list=actor_list, review_list=review_list, rate=rate)


@bp.route('/detail/<int:movie_id>/create', methods=('GET', 'POST'))
@login_required
def create_review(movie_id):
    form = ReviewForm()
    if request.method == 'POST' and form.validate_on_submit():
        movie = Movie.query.get_or_404(movie_id)
        review = Review(title=form.title.data,
                        content=form.content.data,
                        date=datetime.now(),
                        rate=form.rate.data,
                        movie_id=movie.id,
                        member_id=g.member.id)
        db.session.add(review)
        db.session.commit()
        return redirect(url_for('movies.detail', movie_id=movie.id))
    return render_template('client_templates/review_comment.html', form=form)


@bp.route('/detail/<int:movie_id>/<int:review_id>', methods=('GET', 'POST'))
@login_required
def modify_review(movie_id, review_id):
    review_ = Review.query.get(review_id)
    if g.member.id != review_.member_id:
        flash('수정권한이 없습니다.')
        return redirect(url_for('movies.detail', movie_id=movie_id))
    if request.method == 'POST':
        form = ReviewForm()
        if form.validate_on_submit():
            form.populate_obj(review_)
            review_.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('movies.detail', movie_id=movie_id))
    else:
        form = ReviewForm(obj=review_)
    return render_template('client_templates/review_comment.html', form=form)


@bp.route('/detail/<int:movie_id>/delete<int:review_id>')
@login_required
def delete_review(movie_id, review_id):
    review_ = Review.query.get(review_id)
    if g.member.id != review_.member_id:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('movies.detail', movie_id=movie_id))
    db.session.delete(review_)
    db.session.commit()
    return redirect(url_for('movies.detail', movie_id=movie_id))

flex/views/services_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for,g,flash
from werkzeug.utils import redirect

from .. import db
from flex.models import Notice,Inquiry,InquiryAnswer,NoticeAnswer,Question,Answer
from ..forms import QuestionForm, AnswerForm,NoticeForm,NoticeAnswerForm
from .auth_views import login_required
bp = Blueprint('services', __name__, url_prefix='/services')

@bp.route('/')
def _select():

    return render_template('services/services_select.html')




@bp.route('/notice/')
def _notice():
    page = request.args.get('page', type=int, default=1)
    notice_list = Notice.query.order_by(Notice.date.desc())
    notice_list = notice_list.paginate(page, per_page=10)
    return render_template('services/services_notice_list.html', notice_list=notice_list)

@bp.route('/notice/create/', methods=('GET', 'POST'))
def noticeCreate():
    form = NoticeForm()
    if request.method == 'POST' and form.validate_on_submit():
        notice = Notice(title=form.subject.data, content=form.content.data, date=datetime.now(), theater_id = 1)
        db.session.add(notice)
        db.session.commit()
        return redirect(url_for('services._notice'))
    return render_template('question/notice_form.html', form=form)

@bp.route('/notice/<int:notice_id>/')
def noticeDetail(notice_id):
    form = NoticeAnswerForm()
    notice = Notice.query.get_or_404(notice_id)
    return render_template('question/notice_detail.html', notice = notice, form=form)




@bp.route('/inquiry/')
def _inquiry():
    page = request.args.get('page', type=int, default=1)
    inquiry_list = Inquiry.query.order_by(Inquiry.date.desc())
    inquiry_list = inquiry_list.paginate(page, per_page=10)
    return render_template('services/services_question_list.html', inquiry_list=inquiry_list)



@bp.route('/inquiry/create/', methods=('GET', 'POST'))
@login_required
def inquiryCreate():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        inquiry = Inquiry(title=form.subject.data, content=form.content.data, date=datetime.now(),member_id = g.member.id)
        db.session.add(inquiry)
        db.session.commit()
        return redirect(url_for('services._inquiry'))
    return render_template('question/question_form.html', form=form)


@bp.route('/inquiry/<int:inquiry_id>/')
def inquiryDetail(inquiry_id):
    form = AnswerForm()
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    return render_template('question/question_detail.html', inquiry=inquiry, form=form)

@bp.route('/delete/<int:inquiry_id>')
@login_required
def inquiryDelete(inquiry_id):
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    if g.member.id != inquiry.member_id:
        flash('삭제권한이 없습니다')
        return redirect(url_for('services.inquiryDetail', inquiry_id=inquiry_id))
    db.session.delete(inquiry)
    db.session.commit()
    return redirect(url_for('services._inquiry'))

flex/templates/client_base.html
<!--클라이언트(손님) 페이지의 base.html, 모든 손님 페이지에 공통적으로 들어가는 memico css-->
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>도미노 멀티플렉스</title>
    <!-- 챗봇 -->
    <link
      href="{{ url_for('static', filename='client_static/chatbot_static/style.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Bootstrap -->
    <link
      href="{{ url_for('static', filename='client_static/bootstrap/css/bootstrap.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- 이 주러한 주석은 본래 memico꺼, 참고용으로 넣어둠 <link href="./bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />  -->
    <!-- Animate.css -->
    <link
      href="{{ url_for('static', filename='client_static/animate.css/animate.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- <link href="./animate.css/animate.css" rel="stylesheet" type="text/css" /> -->
    <!-- Font Awesome iconic font -->
    <link
      href="{{ url_for('static', filename='client_static/fontawesome/css/fontawesome-all.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- <link href="./fontawesome/css/fontawesome-all.css" rel="stylesheet" type="text/css" /> -->
    <!-- Magnific Popup -->
    <link
      href="{{ url_for('static', filename='client_static/magnific-popup/magnific-popup.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- <link href="./magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css" /> -->
    <!-- Slick carousel -->
    <link
      href="{{ url_for('static', filename='client_static/slick/slick.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- <link href="./slick/slick.css" rel="stylesheet" type="text/css" /> -->
    <!-- Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Theme styles -->
    <link
      href="{{ url_for('static', filename='client_static/css/dot-icons.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{{ url_for('static', filename='client_static/css/theme.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <!--
        <link href="./css/dot-icons.css" rel="stylesheet" type="text/css">
        <link href="./css/theme.css" rel="stylesheet" type="text/css">-->
  </head>
  <body class="body">
    <!-- header는 상단바-->
    <header class="header header-horizontal header-view-pannel">
      <div class="container">
        <nav class="navbar">
          <!-- 메인 아이콘-->
          <a class="navbar-brand" href="{{ url_for('main.init')  }}">
            <span class="logo-element">
              <span class="logo-tape">
                <span class="svg-content svg-fill-theme" , data-svg="">
                  <svg
                    viewBox="0 0 55 43"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    style="height: 1.2em; width: 1.5349em"
                  >
                    <path
                      class="fill-path"
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M8 0H47V3H51V0H55V43H51V40H47V43H8V40H4V43H0V0H4V3H8V0ZM8 7H4V11H8V7ZM4 15H8V19H4V15ZM8 23H4V27H8V23ZM4 32H8V36H4V32ZM51 7H47V11H51V7ZM47 15H51V19H47V15ZM51 23H47V27H51V23ZM47 32H51V36H47V32Z"
                      fill="#FF8A00"
                    />
                  </svg>
                </span>
              </span>
              <span class="logo-text text-uppercase"> <span>D</span>MN</span>
            </span>
          </a>
          <button class="navbar-toggler" type="button">
            <span class="th-dots-active-close th-dots th-bars">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </button>
          <div class="navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item nav-item-arrow-down nav-hover-show-sub">
                <a class="nav-link" href="{{ url_for('movies.list') }}">영화</a>
              </li>
              <li class="nav-item nav-item-arrow-down nav-hover-show-sub">
                <a class="nav-link" href="{{ url_for('theaters.index') }}"
                  >극장</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('services._select') }}">고객센터</a>
              </li>
            </ul>
            <div class="navbar-extra">
              <ul class="navbar-nav">
                <!-- navbar에 로그인, 회원가입 / 로그아웃 탭 추가 -->
                {% if g.member %}
                <!-- 로그인 상태라면 로그아웃 + 마이페이지 탭 노출 -->
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('mypage.mypage') }}"
                    >마이페이지</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.logout') }}"
                    >로그아웃</a
                  >
                </li>
                  {% else %}
                  <!-- 로그인 상태가 아니라면 로그인, 회원가입탭 노출 -->
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login') }}"
                    >로그인</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.signup') }}"
                    >회원가입</a
                  >
                </li>
                {% endif %}
                <li class="nav-item">
                  <a
                    class="btn-theme btn"
                    href="{{ url_for('reservation.ticket') }}"
                    ><i class="fas fa-ticket-alt"></i>&nbsp;&nbsp;빠른예매</a
                  >
                </li>
                <li class="nav-item">
                  <a rel="license" href="https://creativecommons.org/licenses/by/4.0/deed.ko" >
                  <img alt="Creative Commons License" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
<!-- 여기부터 페이지 별 내용 Start -->
{% block content %}
{% endblock %}
<!-- 여기까지 페이지 별 내용 End -->
<a class="scroll-top disabled" href="#"><i class="fas fa-angle-up" aria-hidden="true"></i></a>
<!-- jQuery library -->
<script src="{{ url_for('static', filename='client_static/js/jquery-3.3.1.js') }}"></script>
<!-- Bootstrap -->
<script src="{{url_for('static', filename='client_static/bootstrap/js/bootstrap.js') }}"></script>
<!-- Paralax.js -->
<script src="{{url_for('static', filename='client_static/parallax.js/parallax.js') }}"></script>
<!-- Waypoints -->
<script src="{{url_for('static', filename='client_static/waypoints/jquery.waypoints.min.js') }}"></script>
<!-- Slick carousel -->
<script src="{{url_for('static', filename='client_static/slick/slick.min.js') }}"></script>
<!-- Magnific Popup -->
<script src="{{url_for('static', filename='client_static/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
<script src="{{url_for('static', filename='client_static/js/script.js') }}"></script>
    <!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.4.1.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
<!-- Inits product scripts  구글 맵 api 사용 js 이거 쓰면 계속 refresh돼서 서버 터짐
-->
    <!-- <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJ4Qy67ZAILavdLyYV2ZwlShd0VAqzRXA&callback=initMap"></script> -->
    <script
      async
      defer
      src="https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/js/rating.js"
    ></script>
  </body>
  <footer class="section-text-white footer footer-links bg-darken">
    <div class="footer-body container">
      <div class="row">
        <div class="col-sm-6 col-lg-3">
          <a class="footer-logo" href="./">
            <span class="logo-element">
              <span class="logo-tape">
                <span class="svg-content svg-fill-theme" data-svg="">
                  <svg
                    viewBox="0 0 55 43"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    style="height: 1.2em; width: 1.5349em"
                  >
                    <path
                      class="fill-path"
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M8 0H47V3H51V0H55V43H51V40H47V43H8V40H4V43H0V0H4V3H8V0ZM8 7H4V11H8V7ZM4 15H8V19H4V15ZM8 23H4V27H8V23ZM4 32H8V36H4V32ZM51 7H47V11H51V7ZM47 15H51V19H47V15ZM51 23H47V27H51V23ZM47 32H51V36H47V32Z"
                      fill="#FF8A00"
                    />
                  </svg>
                </span>
              </span>
              <span class="logo-text text-uppercase"> <span> D</span>MN</span>
            </span>
          </a>
          <div class="footer-content">
            <p class="footer-text">
              College of Software, <br />Hanyang Univ ERICA
            </p>
            <p class="footer-text">Call us:&nbsp;&nbsp;(555) 555-0312</p>
          </div>
        </div>
        <div class="col-sm-6 col-lg-3">
          <h5 class="footer-title text-uppercase">Movies</h5>
          <ul class="list-unstyled list-wide footer-content">
            <li>
              <a class="content-link" href="{{ url_for('movies.list') }}"
                >영화목록</a
              >
            </li>
            <li>
              <a class="content-link" href="{{ url_for('reservation.ticket') }}"
                >빠른예매</a
              >
            </li>
            <li>
              <a class="content-link" href="{{ url_for('theaters.index') }}"
                >극장</a
              >
            </li>
          </ul>
        </div>
        <div class="col-sm-6 col-lg-3">
          <h5 class="footer-title text-uppercase">Information</h5>
          <ul class="list-unstyled list-wide footer-content">
            <li>
              <a class="content-link" href="{{ url_for('theaters.index') }}"
                >극장</a
              >
            </li>
          </ul>
        </div>
        <div class="col-sm-6 col-lg-3">
          <h5 class="footer-title text-uppercase">Follow</h5>
          <ul class="list-wide footer-content list-inline">
            <li class="list-inline-item">
              <a class="content-link" href="https://github.com/Gudegi/Database-Theater"
                ><i class="fab fa-github-square"></i
              ></a>
            </li>
          </ul>
          <h5 class="footer-title text-uppercase">Subscribe</h5>
          <div class="footer-content">
            <p class="footer-text">
              Get latest movie news right away with our subscription
            </p>
            <form class="footer-form" autocomplete="off">
              <div class="input-group">
                <input
                  class="form-control"
                  name="email"
                  type="email"
                  placeholder="Your email"
                />
                <div class="input-group-append">
                  <button class="btn btn-theme" type="submit">
                    <i class="fas fa-angle-right"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-copy">
      <div class="container">
        Copyright 2019 &copy; AmigosThemes. All rights reserved.
          <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a
          <a rel="license" href="https://github.com/amigosthemes/memico">Creative Commons Attribution 4.0 International License</a>.
      </div>

    </div>
    <div id = "sidebox">
      <div class="chatbox">
          <div class="chatbox__support">
               <div class="chatbox__header">
                  <div class="chatbox__image--header">
                      <img src="https://img.icons8.com/color/48/000000/circled-user-female-skin-type-5--v1.png" alt="image">
                  </div>
                  <div class="chatbox__content--header">
                      <h4 class="chatbox__heading--header">DMN 챗봇</h4>
                      <p class="chatbox__description--header">안녕하세요. 무엇을 도와드릴까요? </p>
                  </div>
              </div>
              <div class="chatbox__messages">
                  <div></div>
              </div>
              <div class="chatbox__footer">
                  <input type="text" placeholder="   메세지를 입력하세요..">
                  <button class="chatbox__send--footer send__button">전송</button>
              </div>
          </div>
          <div class="chatbox__button">
              <button><img src="{{ url_for('static', filename='client_static/chatbot_static/images/chatbox-icon.svg') }}" /></button>
          </div>
      </div>
      <script src="{{ url_for('static', filename='client_static/chatbot_static/app.js') }}"></script>
      <script>
        var currentPosition = parseInt($("#sidebox").css("top")); 
        $(window).scroll(function() { 
          var position = $(window).scrollTop(); 
          $("#sidebox").stop().animate({"top":position+currentPosition+"px"},1000); 
        });
      </script>
    </div>
  </footer>
</html>

flex/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}