flex/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm,NoticeAnswerForm
from ..models import Notice,NoticeAnswer,InquiryAnswer,Inquiry

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:inquiry_id>', methods=('POST',))
def create(inquiry_id):
    form = AnswerForm()
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = InquiryAnswer(content=content, create_date=datetime.now())
        inquiry.inquiry.append(answer)
        db.session.commit()
        return redirect(url_for('services.inquiryDetail', inquiry_id=inquiry_id))
    return render_template('question/question_detail.html', inquiry=inquiry, form=form)

@bp.route('/noticeCreate/<int:notice_id>', methods=('POST',))
def noticeCreate(notice_id):
    form = NoticeAnswerForm()
    notice = Notice.query.get_or_404(notice_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = NoticeAnswer(content=content, create_date=datetime.now())
        notice.nsa.append(answer)
        db.session.commit()
        return redirect(url_for('services.noticeDetail', notice_id=notice_id))
    return render_template('question/notice_detail.html', notice=notice, form=form)

flex/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

from .. import db
from flex.models import Question
from ..forms import QuestionForm, AnswerForm

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

flex/views/services_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for,g,flash
from werkzeug.utils import redirect

from .. import db
from flex.models import Notice,Inquiry,InquiryAnswer,NoticeAnswer,Question,Answer
from ..forms import QuestionForm, AnswerForm,NoticeForm,NoticeAnswerForm
from .auth_views import login_required
bp = Blueprint('services', __name__, url_prefix='/services')

@bp.route('/')
def _select():

    return render_template('services/services_select.html')




@bp.route('/notice/')
def _notice():
    page = request.args.get('page', type=int, default=1)
    notice_list = Notice.query.order_by(Notice.date.desc())
    notice_list = notice_list.paginate(page, per_page=10)
    return render_template('services/services_notice_list.html', notice_list=notice_list)

@bp.route('/notice/create/', methods=('GET', 'POST'))
def noticeCreate():
    form = NoticeForm()
    if request.method == 'POST' and form.validate_on_submit():
        notice = Notice(title=form.subject.data, content=form.content.data, date=datetime.now(), theater_id = 1)
        db.session.add(notice)
        db.session.commit()
        return redirect(url_for('services._notice'))
    return render_template('question/notice_form.html', form=form)

@bp.route('/notice/<int:notice_id>/')
def noticeDetail(notice_id):
    form = NoticeAnswerForm()
    notice = Notice.query.get_or_404(notice_id)
    return render_template('question/notice_detail.html', notice = notice, form=form)




@bp.route('/inquiry/')
def _inquiry():
    page = request.args.get('page', type=int, default=1)
    inquiry_list = Inquiry.query.order_by(Inquiry.date.desc())
    inquiry_list = inquiry_list.paginate(page, per_page=10)
    return render_template('services/services_question_list.html', inquiry_list=inquiry_list)



@bp.route('/inquiry/create/', methods=('GET', 'POST'))
@login_required
def inquiryCreate():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        inquiry = Inquiry(title=form.subject.data, content=form.content.data, date=datetime.now(),member_id = g.member.id)
        db.session.add(inquiry)
        db.session.commit()
        return redirect(url_for('services._inquiry'))
    return render_template('question/question_form.html', form=form)


@bp.route('/inquiry/<int:inquiry_id>/')
def inquiryDetail(inquiry_id):
    form = AnswerForm()
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    return render_template('question/question_detail.html', inquiry=inquiry, form=form)

@bp.route('/delete/<int:inquiry_id>')
@login_required
def inquiryDelete(inquiry_id):
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    if g.member.id != inquiry.member_id:
        flash('삭제권한이 없습니다')
        return redirect(url_for('services.inquiryDetail', inquiry_id=inquiry_id))
    db.session.delete(inquiry)
    db.session.commit()
    return redirect(url_for('services._inquiry'))

flex/templates/question/notice_detail.html
{% extends 'client_base.html' %}
{% block content %}
<style>
    .btn-primary {
        background-color: #FF8A00;
        border: 1px solid #FF8A00;
    }
</style>
<section class="after-head d-flex section-text-white position-relative">
            <div class="d-background" data-image-src="http://via.placeholder.com/1920x1080" data-parallax="scroll"></div>
            <div class="d-background bg-black-80"></div>
            <div class="top-block top-inner container">
                <div class="top-block-content">
                    <h1 class="section-title">고객센터</h1>
                    <div class="page-breadcrumbs">
                        <a class="content-link" href="#">고객센터</a>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>공지사항</span>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>{{notice.subject}}</span>
                    </div>
                </div>
            </div>
</section>

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ notice.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ notice.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ notice.date|datetime }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ notice.nsa|length }}개의 답변이 있습니다.</h5>
    {% for answer in notice.nsa %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date|datetime }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.noticeCreate', notice_id=notice.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

flex/templates/question/notice_form.html
{% extends 'client_base.html' %}
{% block content %}
<section class="after-head d-flex section-text-white position-relative">
            <div class="d-background" data-image-src="http://via.placeholder.com/1920x1080" data-parallax="scroll"></div>
            <div class="d-background bg-black-80"></div>
            <div class="top-block top-inner container">
                <div class="top-block-content">
                    <h1 class="section-title">고객센터</h1>
                    <div class="page-breadcrumbs">
                        <a class="content-link" href="#">고객센터</a>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>공지사항</span>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>공지등록</span>
                    </div>
                </div>
            </div>
</section>

<div class="container">
    <h5 class="my-3 border-bottom pb-2">공지등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token}}
         <!-- 오류표시 Start -->
         {% for field, errors in form.errors.items() %}
         <div class="alert alert-danger" role="alert">
             <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
         </div>
         {% endfor %}
         <!-- 오류표시 End -->
        <!--{{ form.subject.label }}
        {{ form.subject(class="form-control") }}

        {{ form.content.label }}
        {{ form.content(class="form-control") }}-->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">

        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <hr></hr>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

flex/templates/question/question_detail.html
{% extends 'client_base.html' %}
{% block content %}
<style>
    .btn-primary {
        background-color: #FF8A00;
        border: 1px solid #FF8A00;
    }
</style>
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ inquiry.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ inquiry.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ inquiry.date }}
                </div>
            </div>
            {% if g.member.id == inquiry.member_id %}
                <div class="my-3">
                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{{ url_for('services.inquiryDelete', inquiry_id=inquiry.number) }}">삭제</a>
                </div>
            {% endif %}
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ inquiry.inquiry|length }}개의 답변이 있습니다.</h5>
    {% for answer in inquiry.inquiry %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', inquiry_id=inquiry.number) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

flex/templates/question/question_form.html
{% extends 'client_base.html' %}
{% block content %}
<style>
    .btn-primary {
        background-color: #FF8A00;
        border: 1px solid #FF8A00;
    }
</style>
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token}}
         <!-- 오류표시 Start -->
         {% for field, errors in form.errors.items() %}
         <div class="alert alert-danger" role="alert">
             <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
         </div>
         {% endfor %}
         <!-- 오류표시 End -->
        <!--{{ form.subject.label }}
        {{ form.subject(class="form-control") }}

        {{ form.content.label }}
        {{ form.content(class="form-control") }}-->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
            
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <hr></hr>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

flex/templates/question/question_list.html
{% extends 'client_base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if inquiry_list %}
        {% for inquiry in inquiry_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{ url_for('inquiry.detail', inquiry_id=inquiry.id) }}">{{ inquiry.title }}</a>
            </td>
            <td>{{ inquiry.date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table> 
    <a href="{{ url_for('services.inquiryCreate') }}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}