flex/views/services_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for,g,flash
from werkzeug.utils import redirect

from .. import db
from flex.models import Notice,Inquiry,InquiryAnswer,NoticeAnswer,Question,Answer
from ..forms import QuestionForm, AnswerForm,NoticeForm,NoticeAnswerForm
from .auth_views import login_required
bp = Blueprint('services', __name__, url_prefix='/services')

@bp.route('/')
def _select():

    return render_template('services/services_select.html')




@bp.route('/notice/')
def _notice():
    page = request.args.get('page', type=int, default=1)
    notice_list = Notice.query.order_by(Notice.date.desc())
    notice_list = notice_list.paginate(page, per_page=10)
    return render_template('services/services_notice_list.html', notice_list=notice_list)

@bp.route('/notice/create/', methods=('GET', 'POST'))
def noticeCreate():
    form = NoticeForm()
    if request.method == 'POST' and form.validate_on_submit():
        notice = Notice(title=form.subject.data, content=form.content.data, date=datetime.now(), theater_id = 1)
        db.session.add(notice)
        db.session.commit()
        return redirect(url_for('services._notice'))
    return render_template('question/notice_form.html', form=form)

@bp.route('/notice/<int:notice_id>/')
def noticeDetail(notice_id):
    form = NoticeAnswerForm()
    notice = Notice.query.get_or_404(notice_id)
    return render_template('question/notice_detail.html', notice = notice, form=form)




@bp.route('/inquiry/')
def _inquiry():
    page = request.args.get('page', type=int, default=1)
    inquiry_list = Inquiry.query.order_by(Inquiry.date.desc())
    inquiry_list = inquiry_list.paginate(page, per_page=10)
    return render_template('services/services_question_list.html', inquiry_list=inquiry_list)



@bp.route('/inquiry/create/', methods=('GET', 'POST'))
@login_required
def inquiryCreate():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        inquiry = Inquiry(title=form.subject.data, content=form.content.data, date=datetime.now(),member_id = g.member.id)
        db.session.add(inquiry)
        db.session.commit()
        return redirect(url_for('services._inquiry'))
    return render_template('question/question_form.html', form=form)


@bp.route('/inquiry/<int:inquiry_id>/')
def inquiryDetail(inquiry_id):
    form = AnswerForm()
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    return render_template('question/question_detail.html', inquiry=inquiry, form=form)

@bp.route('/delete/<int:inquiry_id>')
@login_required
def inquiryDelete(inquiry_id):
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    if g.member.id != inquiry.member_id:
        flash('삭제권한이 없습니다')
        return redirect(url_for('services.inquiryDetail', inquiry_id=inquiry_id))
    db.session.delete(inquiry)
    db.session.commit()
    return redirect(url_for('services._inquiry'))

flex/templates/services/services_notice_list.html
{% extends 'client_base.html' %}
{% block content %}
<style>
    .btn-primary{
        background-color: #FF8A00;
        border:1px solid #FF8A00;
    }

    .is-active,
    [aria-current="page"] {
      background: #333;
      color: #fff;
    }

    .page-link {
    position: relative;
    display: block;
    padding: 0.5rem 0.75rem;
    margin-left: -1px;
    line-height: 1.25;
    color: #FF8A00;
    background-color: #fff;
    border: 1px solid #dee2e6;
    }

    .page-link:hover {
    z-index: 2;
    color: #FF8A00;
    text-decoration: none;
    background-color: #e9ecef;
    border-color: #dee2e6;
    }

    .page-link:focus {
    z-index: 2;
    outline: 0;
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

    .page-link:not(:disabled):not(.disabled) {
    cursor: pointer;
    }

    .page-item:first-child .page-link {
    margin-left: 0;
    border-top-left-radius: 0.25rem;
    border-bottom-left-radius: 0.25rem;
    }

    .page-item:last-child .page-link {
    border-top-right-radius: 0.25rem;
    border-bottom-right-radius: 0.25rem;
    }

    .page-item.active .page-link {
    z-index: 1;
    color: #fff;
    background-color: #FF8A00;
    border-color: #FF8A00;
    }

    .page-item.disabled .page-link {
    color: #6c757d;
    pointer-events: none;
    cursor: auto;
    background-color: #fff;
    border-color: #dee2e6;
    }
</style>
<section class="after-head d-flex section-text-white position-relative">
            <div class="d-background" data-image-src="\static\img\serviceSelect.jpg" data-parallax="scroll"></div>
            <div class="d-background bg-black-80"></div>
            <div class="top-block top-inner container">
                <div class="top-block-content">
                    <h1 class="section-title">고객센터</h1>
                    <div class="page-breadcrumbs">
                        <a class="content-link" href="#">고객센터</a>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>공지사항</span>
                    </div>
                </div>
            </div>
</section>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>작성일시</th>
            <th>지점</th>
            <th>댓글 수</th>

        </tr>
        </thead>
        <tbody>
        {% if notice_list %}
        {% for notice in notice_list.items %}
        <tr class="text-center">
            <td>{{ notice_list.total - ((notice_list.page-1) * notice_list.per_page) - loop.index0 }}</td>
            <td class="text-left">
                <a href="{{ url_for('services.noticeDetail', notice_id=notice.id) }}"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ notice.title }}</a>
            </td>
            <td>{{ notice.date|datetime }}</td>
            {%if notice.theater_id==1 %}
                <td>강남점</td>
            {% endif %}
            {%if notice.theater_id==2 %}
                <td>이태원점</td>
            {% endif %}
            {%if notice.theater_id==3 %}
                <td>금호점</td>
            {% endif %}
            {%if notice.theater_id==4 %}
                <td>한양대점</td>
            {% endif %}
            {%if notice.theater_id==5 %}
                <td>홍대점</td>
            {% endif %}







            <td>
            {% if notice.nsa|length > 0 %}
                <span class="text-danger small ml-2">{{ notice.nsa|length }}</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">공지가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if notice_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ notice_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in notice_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != notice_list.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if notice_list.has_next %}
        <li class="page-item" >
            <a class="page-link" href="?page={{ notice_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <!--<a href="{{ url_for('services.noticeCreate') }}" class="btn btn-primary">공지 등록하기</a>-->
</div>


{% endblock %}

flex/templates/services/services_question_list.html
{% extends 'client_base.html' %} {% block content %}

<style>
  .btn-primary{
      background-color: #FF8A00;
      border:1px solid #FF8A00;
  }

  .is-active,
  [aria-current="page"] {
    background: #333;
    color: #fff;
  }

  .page-link {
  position: relative;
  display: block;
  padding: 0.5rem 0.75rem;
  margin-left: -1px;
  line-height: 1.25;
  color: #FF8A00;
  background-color: #fff;
  border: 1px solid #dee2e6;
  }

  .page-link:hover {
  z-index: 2;
  color: #FF8A00;
  text-decoration: none;
  background-color: #e9ecef;
  border-color: #dee2e6;
  }

  .page-link:focus {
  z-index: 2;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
  }

  .page-link:not(:disabled):not(.disabled) {
  cursor: pointer;
  }

  .page-item:first-child .page-link {
  margin-left: 0;
  border-top-left-radius: 0.25rem;
  border-bottom-left-radius: 0.25rem;
  }

  .page-item:last-child .page-link {
  border-top-right-radius: 0.25rem;
  border-bottom-right-radius: 0.25rem;
  }

  .page-item.active .page-link {
  z-index: 1;
  color: #fff;
  background-color: #FF8A00;
  border-color: #FF8A00;
  }

  .page-item.disabled .page-link {
  color: #6c757d;
  pointer-events: none;
  cursor: auto;
  background-color: #fff;
  border-color: #dee2e6;
  }
</style>
<section class="after-head d-flex section-text-white position-relative">
  <div
    class="d-background"
    data-image-src="\static\img\serviceSelect.jpg"
    data-parallax="scroll"
  ></div>
  <div class="d-background bg-black-80"></div>
  <div class="top-block top-inner container">
    <div class="top-block-content">
      <h1 class="section-title">고객센터</h1>
      <div class="page-breadcrumbs">
        <a class="content-link" href="#">고객센터</a>
        <span class="text-theme mx-2"
          ><i class="fas fa-chevron-right"></i
        ></span>
        <span>문의사항</span>
      </div>
    </div>
  </div>
</section>

<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="text-center thead-dark">
        <th>번호</th>
        <th style="width: 50%">제목</th>
        <th>글쓴이</th>
        <th>작성일시</th>
        <th>댓글 수</th>
      </tr>
    </thead>
    <tbody>
      {% if inquiry_list %} {% for inquiry in inquiry_list.items %}
      <tr class="text-center">
        <td>
          {{ inquiry_list.total - ((inquiry_list.page-1) *
          inquiry_list.per_page) - loop.index0 }}
        </td>
        <td class="text-left">
          <a
            href="{{ url_for('services.inquiryDetail', inquiry_id=inquiry.number) }}"
            }
            >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{inquiry.title }}</a
          >
        </td>
        <td>{{ inquiry.member_id }}</td>
        <td>{{ inquiry.date|datetime }}</td>
        <td>
          {% if inquiry.inquiry|length > 0 %}
          <span class="text-danger small ml-2"
            >{{ inquiry.inquiry|length }}</span
          >
          {% endif %}
        </td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if inquiry_list.has_prev %}
    <li class="page-item">
      <a class="page-link" href="?page={{ inquiry_list.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %} {% for page_num in inquiry_list.iter_pages() %} {% if page_num
    %} {% if page_num != inquiry_list.page %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% endif %} {% else %}
    <li class="disabled">
      <a class="page-link" href="#">...</a>
    </li>
    {% endif %} {% endfor %}
    <!-- 다음페이지 -->
    {% if inquiry_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ inquiry_list.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
  <a href="{{ url_for('services.inquiryCreate') }}" class="btn btn-primary"
    >질문 등록하기</a
  >
</div>

{% endblock %}

flex/templates/services/services_select.html
{% extends 'client_base.html' %} {% block content %}
<section class="after-head d-flex section-text-white position-relative">
  <div
    class="d-background"
    data-image-src="\static\img\serviceSelect.jpg"
    data-parallax="scroll"
  ></div>
  <div class="d-background bg-black-80"></div>
  <div class="top-block top-inner container">
    <div class="top-block-content">
      <h1 class="section-title">고객센터</h1>
      <div class="page-breadcrumbs">
        <a class="content-link" href="#">고객센터</a>
      </div>
    </div>
  </div>
</section>
<section class="section-long">
  <div class="container">
    <div class="section-head" style="margin-top: -3rem">
      <h2 class="section-title text-uppercase">고객센터 홈</h2>
      <p class="section-text">
        DMN 고객센터입니다. 문의 사항이 있으시면 메뉴를 선택해주세요.
      </p>
    </div>
    <div class="container my-5">
      <div class="row justify-content-center mt-5">
        <div class="col-lg-9">
          <div class="row" style="text-align: center">
            <div class="col">
              <div class="card">
                <div class="card-body pb-0">
                  <div class="showtime-item" style="margin-bottom: 1rem">
                    <a
                      class="btn btn-time"
                      href="{{ url_for('services._notice') }}"
                      style="width: 350px; height: 100px"
                      ><h3>공지사항</h3>
                      <br />지점별 공지 사항들을 확인하세요</a
                    >
                    <a
                      href="{{ url_for('services._inquiry') }}"
                      class="btn btn-time"
                      style="width: 350px; height: 100px"
                      ><h3>문의하기</h3>
                      <br />영화 예매, 취소 등 고객님들의 문의를 받고
                      있습니다.</a
                    >
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}