flex/views/main_views.py
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect
from flex.models import Movie, Review
import datetime

bp = Blueprint('main', __name__, url_prefix='/')



@bp.route('/hello')
def hello_flex():
    return 'flexxxx'

@bp.route('/')
def init():
    movie_list = Movie.query.order_by(Movie.id.desc())
    rate_list = []
    for movie in movie_list:
        this_list = []
        review_list = Review.query.filter(Review.movie_id == movie.id).all()
        sum = 0
        num = 0
        for review in review_list:
            sum += review.rate
            num += 1
        if (num > 0):
            rate = round(sum / num, 2)
        else:
            rate = 0
        this_list.append(movie)
        this_list.append(rate)
        rate_list.append(this_list)
    today = datetime.date.today().strftime('%Y/%m/%d')
    return render_template('client_templates/homepage-1.html', movie_list=rate_list, today=today)

@bp.route('/client_init')
def index():
    return render_template('client_templates/homepage-1.html')

flex/views/movies_views.py
from flask import Blueprint, url_for, render_template, g, request, flash
from werkzeug.utils import redirect

from datetime import datetime

from ..views.auth_views import login_required

from flex import db
from flex.forms import ReviewForm
from flex.models import Movie, Actor, Review

bp = Blueprint('movies', __name__, url_prefix='/movies')

#영화 목록 페이지
@bp.route('/')
def list():
    movie_list = Movie.query.order_by(Movie.id.asc())
    rate_list = []
    for movie in movie_list:
        this_list = []
        review_list = Review.query.filter(Review.movie_id == movie.id).all()
        sum = 0
        num = 0
        for review in review_list:
            sum += review.rate
            num += 1
        if(num > 0):
            rate = round(sum / num, 2)
        else:
            rate = 0
        this_list.append(movie)
        this_list.append(rate)
        rate_list.append(this_list)
    return render_template('client_templates/movies-list.html', rate_list=rate_list)

#영화 목록 페이지에서 영화 이름 누르면 해당 영화 detail 페이지 랜더링, 각 영화의 이미지, 이름 등 db에 있는 정보들을 인자로 넘겨서 랜더링

@bp.route('/detail/<int:movie_id>')
def detail(movie_id):
    movie = Movie.query.get(movie_id)
    actor_list = Actor.query.filter(Actor.movie_id == movie_id).all()
    review_list = Review.query.filter(Review.movie_id == movie_id).all()
    sum = 0
    for review in review_list:
        sum += review.rate
    if len(review_list) != 0:
        rate = round(sum / len(review_list),2)
    else:
        rate = 0
    return render_template('client_templates/movie-info-sidebar-right.html', movie=movie, actor_list=actor_list, review_list=review_list, rate=rate)


@bp.route('/detail/<int:movie_id>/create', methods=('GET', 'POST'))
@login_required
def create_review(movie_id):
    form = ReviewForm()
    if request.method == 'POST' and form.validate_on_submit():
        movie = Movie.query.get_or_404(movie_id)
        review = Review(title=form.title.data,
                        content=form.content.data,
                        date=datetime.now(),
                        rate=form.rate.data,
                        movie_id=movie.id,
                        member_id=g.member.id)
        db.session.add(review)
        db.session.commit()
        return redirect(url_for('movies.detail', movie_id=movie.id))
    return render_template('client_templates/review_comment.html', form=form)


@bp.route('/detail/<int:movie_id>/<int:review_id>', methods=('GET', 'POST'))
@login_required
def modify_review(movie_id, review_id):
    review_ = Review.query.get(review_id)
    if g.member.id != review_.member_id:
        flash('수정권한이 없습니다.')
        return redirect(url_for('movies.detail', movie_id=movie_id))
    if request.method == 'POST':
        form = ReviewForm()
        if form.validate_on_submit():
            form.populate_obj(review_)
            review_.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('movies.detail', movie_id=movie_id))
    else:
        form = ReviewForm(obj=review_)
    return render_template('client_templates/review_comment.html', form=form)


@bp.route('/detail/<int:movie_id>/delete<int:review_id>')
@login_required
def delete_review(movie_id, review_id):
    review_ = Review.query.get(review_id)
    if g.member.id != review_.member_id:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('movies.detail', movie_id=movie_id))
    db.session.delete(review_)
    db.session.commit()
    return redirect(url_for('movies.detail', movie_id=movie_id))

flex/views/mypage_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g, flash
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import datetime

from flex import db
from flex.models import Movie, Screenschedule, Theater,  Seat, Membership,  Benefit,  Reservation, \
    Pay, IsUsed, Screen, Cancel, Member
from flex.forms import ReservationCancelForm

bp = Blueprint('mypage', __name__, url_prefix='/mypage')


@bp.route('/')
def mypage():
    member_id = -1
    if g.member:
        member_id = g.member.id
    else:
        return redirect(url_for('main.init'))  # 로그인 안한상태면 메인화면으로 보냄.
    member = Member.query.get(member_id)
    membership = Membership.query.filter(Membership.member_id == member_id).first()
    res_list = Reservation.query.filter(Reservation.member_id == member_id).all()
    history_list = []
    future_list = []

    for i in range(len(res_list)):
        this_list = []
        this_schedule = Screenschedule.query.get(res_list[i].screen_schedule_id)
        if len(Cancel.query.filter(Cancel.res_id == res_list[i].id).all()) == 0:  # 취소가 안된 영화만
            this_list.append(res_list[i])  # list[][0] Reservation
            this_list.append(Movie.query.get(this_schedule.movie_id))  # list[][1] Movie
            this_list.append(this_schedule)  # list[0][2] Schedule
            seat_list = res_list[i].seats.split()
            query_seat_list = []
            for j in range(len(seat_list)):
                seat = Seat.query.get(seat_list[j])
                query_seat_list.append(seat)
            this_list.append(query_seat_list)
            this_list.append(Theater.query.get(this_schedule.theater_id))
            this_list.append(Screen.query.get(this_schedule.screen_number))
            date_diff = datetime.datetime.now() - this_schedule.starttime
            if this_schedule.starttime > datetime.datetime.now():
                future_list.append(this_list)
            elif date_diff < datetime.timedelta(days=32):
                history_list.append(this_list)
    history_num = len(history_list)
    future_num = len(future_list)
    return render_template('client_templates/reservation-check.html', future_list=future_list,
                           history_list=history_list,
                           history_num=history_num, future_num=future_num, member=member, membership=membership)


@bp.route('/<int:res_id>', methods=('POST', 'GET'))
def cancel(res_id):
    member_id = -1
    if g.member:
        member_id = g.member.id
    else:
        return redirect(url_for('main.init'))  # 로그인 안한상태면 메인화면으로 보냄.
    reservation = Reservation.query.get(res_id)
    schedule = Screenschedule.query.get(reservation.screen_schedule_id)
    movie = Movie.query.get(schedule.movie_id)
    membership = Membership.query.filter(Membership.member_id == member_id).first()
    screen = Screen.query.get(schedule.screen_number)
    pay = Pay.query.filter(Pay.reservation_id == res_id).first()
    seat_list = reservation.seats.split()
    theater_name = Theater.query.get(schedule.theater_id)
    query_seat_list = []
    coupon_value = 0
    form = ReservationCancelForm()
    if pay.coupon_code != "-1":
        coupon_value = Benefit.query.get(pay.coupon_code).benefit
    for j in range(len(seat_list)):
        seat = Seat.query.get(seat_list[j])
        query_seat_list.append(seat)
    if request.method == 'POST' and form.validate_on_submit():
        if pay.coupon_code != "-1":
            is_used = IsUsed.query.filter(IsUsed.membership_id == membership.id, IsUsed.coupon_code == pay.coupon_code).first()
            is_used.issued = 0
            db.session.add(is_used)
        for seat in query_seat_list:
            seat.available=1
            db.session.add(seat)
        cancel = Cancel(cancelpay=pay.firstpay,
                        datetime=datetime.datetime.now(),
                        pay_number=pay.number,
                        res_id=reservation.id)
        membership.point += pay.used_points
        db.session.add(cancel)
        db.session.commit()
        return redirect((url_for('mypage.mypage')))
    return render_template('client_templates/cancel-reservation.html', reservation = reservation, schedule = schedule, movie = movie,
                           pay = pay, query_seat_list = query_seat_list, theater_name=theater_name, screen=screen, coupon_value = coupon_value, form=form)

flex/views/services_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for,g,flash
from werkzeug.utils import redirect

from .. import db
from flex.models import Notice,Inquiry,InquiryAnswer,NoticeAnswer,Question,Answer
from ..forms import QuestionForm, AnswerForm,NoticeForm,NoticeAnswerForm
from .auth_views import login_required
bp = Blueprint('services', __name__, url_prefix='/services')

@bp.route('/')
def _select():

    return render_template('services/services_select.html')




@bp.route('/notice/')
def _notice():
    page = request.args.get('page', type=int, default=1)
    notice_list = Notice.query.order_by(Notice.date.desc())
    notice_list = notice_list.paginate(page, per_page=10)
    return render_template('services/services_notice_list.html', notice_list=notice_list)

@bp.route('/notice/create/', methods=('GET', 'POST'))
def noticeCreate():
    form = NoticeForm()
    if request.method == 'POST' and form.validate_on_submit():
        notice = Notice(title=form.subject.data, content=form.content.data, date=datetime.now(), theater_id = 1)
        db.session.add(notice)
        db.session.commit()
        return redirect(url_for('services._notice'))
    return render_template('question/notice_form.html', form=form)

@bp.route('/notice/<int:notice_id>/')
def noticeDetail(notice_id):
    form = NoticeAnswerForm()
    notice = Notice.query.get_or_404(notice_id)
    return render_template('question/notice_detail.html', notice = notice, form=form)




@bp.route('/inquiry/')
def _inquiry():
    page = request.args.get('page', type=int, default=1)
    inquiry_list = Inquiry.query.order_by(Inquiry.date.desc())
    inquiry_list = inquiry_list.paginate(page, per_page=10)
    return render_template('services/services_question_list.html', inquiry_list=inquiry_list)



@bp.route('/inquiry/create/', methods=('GET', 'POST'))
@login_required
def inquiryCreate():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        inquiry = Inquiry(title=form.subject.data, content=form.content.data, date=datetime.now(),member_id = g.member.id)
        db.session.add(inquiry)
        db.session.commit()
        return redirect(url_for('services._inquiry'))
    return render_template('question/question_form.html', form=form)


@bp.route('/inquiry/<int:inquiry_id>/')
def inquiryDetail(inquiry_id):
    form = AnswerForm()
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    return render_template('question/question_detail.html', inquiry=inquiry, form=form)

@bp.route('/delete/<int:inquiry_id>')
@login_required
def inquiryDelete(inquiry_id):
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    if g.member.id != inquiry.member_id:
        flash('삭제권한이 없습니다')
        return redirect(url_for('services.inquiryDetail', inquiry_id=inquiry_id))
    db.session.delete(inquiry)
    db.session.commit()
    return redirect(url_for('services._inquiry'))

flex/views/theaters_views.py
from flask import Blueprint, render_template, request
from datetime import datetime, timedelta
from werkzeug.utils import redirect
from flex.models import Theater, Screenschedule, Movie, Seat, Notice
from sqlalchemy import and_

bp = Blueprint('theaters', __name__, url_prefix='/theaters')

@bp.route('/', methods=['GET'])
def index():
    theaters = Theater.query.get(1)
    notices = Notice.query.filter(Notice.theater_id == 1).order_by(Notice.date.desc()) # 지점 공지 등록 날짜순으로 내림차순 정렬
    week = {0:'월요일', 1:'화요일', 2:'수요일', 3:'목요일', 4:'금요일', 5:'토요일', 6:'일요일'}
    week_list = []
    now = datetime.now()
    now_weekday = now.weekday()

    args = request.args
    selected_date = args.get('date', now.strftime('%Y-%m-%d'))
    selected_theater_id = theaters.id

    # 오늘부터 다음주까지의 요일을 표시
    for i in range(now_weekday, now_weekday+7):
        day = i - now_weekday
        date = now + timedelta(days=day)
        i %= 7
        week_list.append({'weekday' : week[i], 'date':date.strftime('%Y-%m-%d')})

    # 해당 극장에서 상영중인 영화만 보여줌
    movies = Movie.query.join(Screenschedule, and_(Screenschedule.movie_id == Movie.id, Screenschedule.theater_id == selected_theater_id)).filter_by(movie_id=Screenschedule.movie_id).all()
    movie_list = []
    for movie in movies:
        screenschedule_list = []
        screenschedules = Screenschedule.query.filter(Screenschedule.movie_id == movie.id).\
                filter(Screenschedule.theater_id == selected_theater_id).order_by(Screenschedule.starttime.asc())
        for screenschedule in screenschedules:
            # 잔여 좌석수 계산
            seat_cnt = Seat.query.filter(Seat.screen_number == screenschedule.screen_number).\
                filter(Seat.schedule_id == screenschedule.id).\
                    filter(Seat.available == 1).count()
            # 총 좌석수 계산
            tot_seat = Seat.query.filter(Seat.screen_number == screenschedule.screen_number).\
                filter(Seat.schedule_id == screenschedule.id).count()
            screenschedule_list.append(dict(id=screenschedule.id, starttime=screenschedule.starttime, endtime=screenschedule.endtime, session=screenschedule.session, screen=dict(number=screenschedule.screen.number, tot_seat=tot_seat, seat=seat_cnt, name=screenschedule.screen.name)))
        movie_list.append(dict(id=movie.id, title=movie.title, age=movie.age, running_time=movie.running_time, genre=movie.genre, screenschedules=screenschedule_list))
 
    return render_template('client_templates/theaters.html', theaters=theaters, date=selected_date, week_list=week_list, now=datetime.now(), movies=movie_list, notices=notices)
    

@bp.route('/<int:theater_id>')
def other(theater_id):
    theaters = Theater.query.get(theater_id)
    notices = Notice.query.filter(Notice.theater_id == theater_id).order_by(Notice.date.desc())
    week = {0:'월요일', 1:'화요일', 2:'수요일', 3:'목요일', 4:'금요일', 5:'토요일', 6:'일요일'}
    week_list = []
    now = datetime.now()
    now_weekday = now.weekday()

    args = request.args
    selected_date = args.get('date', now.strftime('%Y-%m-%d'))
    selected_theater_id = theaters.id

    # 오늘부터 다음주까지의 요일을 표시
    for i in range(now_weekday, now_weekday+7):
        day = i - now_weekday
        date = now + timedelta(days=day)
        i %= 7
        week_list.append({'weekday' : week[i], 'date':date.strftime('%Y-%m-%d')})

    # 해당 극장에서 상영중인 영화만 보여줌
    movies = Movie.query.join(Screenschedule, and_(Screenschedule.movie_id == Movie.id, Screenschedule.theater_id == selected_theater_id)).filter_by(movie_id=Screenschedule.movie_id).all()
    movie_list = []
    for movie in movies:
        screenschedule_list = []
        screenschedules = Screenschedule.query.filter(Screenschedule.movie_id == movie.id).\
                filter(Screenschedule.theater_id == selected_theater_id).order_by(Screenschedule.starttime.asc())
        for screenschedule in screenschedules:
            # 잔여 좌석수 계산
            seat_cnt = Seat.query.filter(Seat.screen_number == screenschedule.screen_number).\
                filter(Seat.schedule_id == screenschedule.id).\
                    filter(Seat.available == 1).count()
            # 총 좌석수 계산
            tot_seat = Seat.query.filter(Seat.screen_number == screenschedule.screen_number).\
                filter(Seat.schedule_id == screenschedule.id).count()
            screenschedule_list.append(dict(id=screenschedule.id, starttime=screenschedule.starttime, endtime=screenschedule.endtime, session=screenschedule.session, screen=dict(number=screenschedule.screen.number, tot_seat=tot_seat, seat=seat_cnt, name=screenschedule.screen.name)))
        movie_list.append(dict(id=movie.id, title=movie.title, age=movie.age, running_time=movie.running_time, genre=movie.genre, screenschedules=screenschedule_list))

    return render_template('client_templates/theaters.html', theaters=theaters, date=selected_date, week_list=week_list, now=datetime.now(), movies=movie_list, notices=notices)

flex/templates/client_templates/404-1.html
{% extends 'client_base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <body class="body">
        <section class="after-head d-flex section-text-white position-relative">
            <div class="d-background" data-image-src="http://via.placeholder.com/1920x1080" data-parallax="scroll"></div>
            <div class="d-background bg-black-80"></div>
            <div class="top-block top-inner container">
                <div class="top-block-content">
                    <h1 class="section-title">Page not found</h1>
                    <div class="page-breadcrumbs">
                        <a class="content-link" href="#">Home</a>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>Error</span>
                    </div>
                </div>
            </div>
        </section>
        <section class="section-long">
            <div class="container">
                <div class="status-entity">
                    <div class="entity-icon">4<span class="text-theme">0</span>4</div>
                    <h4 class="entity-title">Sorry!</h4>
                    <p class="entity-text">It looks like this page no longer exists</p>
                    <div class="entity-actions">
                        <a class="btn btn-theme" href="{{ url_for('main.init')  }}">홈 화면으로</a>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>
{% endblock %}

flex/templates/client_templates/theaters.html
{% extends 'client_base.html' %} 
{% block content %}
<!DOCTYPE html>
<html>
  <body class="body">
    <section class="after-head d-flex section-text-white position-relative">
      <div class="d-background"
      data-image-src="../../static/client_static/images/Theater_background.jpg"
      data-parallax="scroll"></div>
      <div class="d-background bg-black-80"></div>
      <div class="top-block top-inner container">
        <div class="top-block-content">
          <h1 class="section-title">극장</h1>
          <div class="page-breadcrumbs">
            <a class="content-link" href="#">Home</a>
            <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
            <span>Theater</span>
          </div>
        </div>
      </div>
    </section>
    <section class="section-divbar">
      <div class="container">
        <div class="section-pannel" style="border-radius: 15px;">
        <div class="showtime-wrap" style="margin-top: 0.1rem;">
          <div class="col">
            {%if theaters.id == 1 %}
            <span class="btn-time btn"
            aria-disabled="true"
            style="background-color: coral;">강남점</span>
            {% else %}
            <a class="btn-time btn"
            aria-disabled="false"
            href="{{ url_for('theaters.index') }}">강남점</a>
            {% endif %}
          </div>
          <div class="col">
            {%if theaters.id == 2 %}
            <span class="btn-time btn"
            aria-disabled="true"
            style="background-color: coral;">이태원점</span>
            {% else %}
            <a class="btn-time btn"
            aria-disabled="false"
            href="{{ url_for('theaters.other', theater_id = 2) }}">이태원점</a>
            {% endif %}
          </div>
          <div class="col">
            {%if theaters.id == 3 %}
            <span class="btn-time btn"
            aria-disabled="true"
            style="background-color: coral;">금호점</span>
            {% else %}
            <a class="btn-time btn"
            aria-disabled="false"
            href="{{ url_for('theaters.other', theater_id = 3) }}">금호점</a>
            {% endif %}
          </div>
          <div class="col">
            {%if theaters.id == 4 %}
            <span class="btn-time btn"
            aria-disabled="true"
            style="background-color: coral;">한양대점</span>
            {% else %}
            <a class="btn-time btn"
            aria-disabled="false"
            href="{{ url_for('theaters.other', theater_id = 4) }}">한양대점</a>
            {% endif %}
          </div>
          <div class="col">
            {%if theaters.id == 5 %}
            <span class="btn-time btn"
            aria-disabled="true"
            style="background-color: coral;">홍대점</span>
            {% else %}
            <a class="btn-time btn"
            aria-disabled="false"
            href="{{ url_for('theaters.other', theater_id = 5) }}">홍대점</a>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
    <section class="section-middle">
      <div class="container">
        <div class="section-head">
          <h2 class="section-title text-uppercase"><b>DMN {{ theaters.name }}</b></h2>
          {%if theaters.id == 1 %}
          <p class="section-text">로맨틱 멀티플렉스! 젊은 도시 강남이 한 눈에 보이는 최상의 View를 제공</p>
          {% endif %}
          {%if theaters.id == 2 %}
          <p class="section-text">이태원에서 가장 큰 상영관에서 압도되는 영상을 경험하세요.</p>
          {% endif %}
          {%if theaters.id == 3 %}
          <p class="section-text">금호역 도보 5분 거리에 위치!
            {{theaters.screen}}개관 총 {{theaters.seat}}석 규모! 250석의 대형 상영관에서 생생한 관람을!</p>
          {% endif %}
          {%if theaters.id == 4 %}
          <p class="section-text">한대앞역 도보 5분 거리에 위치! 쾌적한 관람을 위한 전관 가죽시트 도입!</p>
          {% endif %}
          {%if theaters.id == 5 %}
          <p class="section-text">글로벌 핵인싸들의 놀이터! 홍대입구역 도보 5분 거리에 위치!</p>
          {% endif %}
        </div>
        <article class="movie-line-entity">
          <div class="entity-theater" data-role="hover-wrap">
            <div class="embed-responsive embed-responsive-poster" style="width: 1088px; height: 420px;">
                <img class="embed-responsive-item" src="../../static/client_static/images/Theater_{{ theaters.name }}.jpg" alt="http://via.placeholder.com/340x510" />
            </div>
          </div>
          <div class="entity-content">
            주소 : {{ theaters.address }}
            <br>전화번호 : {{ theaters.tel }}<br>대표 : {{ theaters.representive }}<br>{{ theaters.screen }}관 / {{ theaters.seat }}석
          </div>
        </article>
      </div>
    </section>
    <section class="section-middle">
      <div class="container">
        <div class="section-head" style="margin-bottom: 2rem;">
          <h4 class="section-title"><b>공지사항 </b><a class="fas fa-plus-square" href="{{ url_for('services._notice') }}"></a></h4>
          <p class="section-text"></p>
        </div>
        <article class="movie-line-entity">
          <div class="entity-content">
            <ul style="list-style: none">
              {% for i in range(2) %}
              <li>
                <a style="color: #666666" href="{{ url_for('services.noticeDetail', notice_id=notices[i].id) }}">[{{theaters.name}}] {{notices[i].title}}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </article>
      </div>
    </section>
    <section class="section-middle">
      <div class="container">
        <div class="section-head" style="margin-bottom: 2rem;">
          <h4 class="section-title"><b>상영시간표</b></h4>
          <p class="section-text"></p>
        </div>
      <div class="container">
        <ul class="nav nav-tabs">
          {% for week in week_list %}
          <li class="nav-item">
            {% if week['date'] == date %}
            <a class="nav-link active" data-toggle="tab" href="#{{ week['weekday'] }}">{{ week['weekday'] }}</a>
            {% else %}
            <a class="nav-link" data-toggle="tab" href="#{{ week['weekday'] }}">{{ week['weekday'] }}</a>
            {% endif %}
          </li>
          {% endfor %}
        </ul>
        <div class="tab-content">
          {% for week in week_list %}
            <div class="tab-pane fade {% if week['date'] == date %}show active{% endif %}" id="{{ week['weekday'] }}">
              <ul class="list-group list-group-flush">
                {% for movie in movies %}
                  <li class="list-group-item" style="padding-left: 0.5em;">
                    <b>{{ movie.title }}</b> / {{ movie.genre }} / {{ movie.running_time }} 분 / {{ movie.age }} 이상 관람가 
                  </li>
                  <div class="showtime-wrap" style="margin-top:0.1rem; margin-bottom: 0.5rem;">
                    {% for screenschedule in movie.screenschedules %}
                      {% if screenschedule.starttime.strftime('%Y-%m-%d') == week['date'] %}
                        {% if now < screenschedule.starttime %}
                          {% if screenschedule.screen.seat < 1 %}
                          <!-- 잔여좌석수 0일시 매진 표시 -->
                          <div class="showtime-item">
                            <a class="btn-time btn disabled" href="#" >
                            {{ screenschedule.starttime.strftime('%H:%M') }} ~ {{ screenschedule.endtime.strftime('%H:%M') }}<br>매진
                            </a>
                          </div>
                          {% else %}           
                          <div class="showtime-item"> 
                          <!-- hover시 관/회차/잔여좌석수 표시 -->
                            <a class="btn-time btn" href="{{ url_for('reservation.seat', movie_id=movie.id, res_date=screenschedule.starttime, theater_name=theaters.id, schedule_id=screenschedule.id ) }}" onMouseOver="this.innerHTML='{{ screenschedule.screen.name }} {{ screenschedule.session }}회차<br>총 {{screenschedule.screen.tot_seat}}석'" onMouseOut="this.innerHTML='{{ screenschedule.starttime.strftime('%H:%M') }} ~ {{ screenschedule.endtime.strftime('%H:%M')}}<br>{{screenschedule.screen.seat}}석'">
                            {{ screenschedule.starttime.strftime('%H:%M') }} ~ {{ screenschedule.endtime.strftime('%H:%M') }}<br>{{screenschedule.screen.seat}}석
                            </a>
                          </div>
                          {% endif %}
                        {% else %}
                        <!-- 상영시간이 현재 시간보다 이전일 경우, 예매 마감 표시 -->
                        <div class="showtime-item">
                          <a class="btn-time btn disabled" href="#">
                          {{ screenschedule.starttime.strftime('%H:%M') }} ~ {{ screenschedule.endtime.strftime('%H:%M') }} <br>마감
                          </a>
                        </div>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  </div>
                {% endfor %}
              </ul>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </body>
</html>
{% endblock %}

flex/templates/client_templates/under-construction.html
{% extends 'client_base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <body class="body">
        <section class="after-head d-flex section-text-white position-relative">
            <div class="d-background" data-image-src="http://via.placeholder.com/1920x1080" data-parallax="scroll"></div>
            <div class="d-background bg-black-80"></div>
            <div class="top-block top-inner container">
                <div class="top-block-content">
                    <h1 class="section-title">Under construction</h1>
                    <div class="page-breadcrumbs">
                        <a class="content-link" href="#">Home</a>
                        <span class="text-theme mx-2"><i class="fas fa-chevron-right"></i></span>
                        <span>Under construction</span>
                    </div>
                </div>
            </div>
        </section>
        <section class="section-long">
            <div class="container">
                <div class="status-entity">
                    <div class="entity-icon"><i class="fas fa-cogs opacity-20"></i></div>
                    <h4 class="entity-title">Under construction</h4>
                    <p class="entity-text">We are working hard to bring it to you</p>
                    <div class="entity-actions">
                        <a class="btn btn-theme" href="#">Back To Homepage</a>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>
{% endblock %}